OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Models/Vodka.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VodkaDelivery.Web.Models
{
    //Form model
    public class Vodka
    {
        [Display( Name = "Vodka ID")]
        [Required]
        public int ID { get; set; }

        [Display(Name = "Company ID")]
        [Required]
        public int Company_ID { get; set; }

        [Display(Name = "Vodka Name")]
        [Required]
        public string VodkaName { get; set; }

        [Display(Name = "Number Of Destills")]
        [Required]
        public int NumberOfDestills { get; set; }

        [Display(Name = "Vodka Price")]
        [Required]
        public int Price { get; set; }

        [Display(Name = "Vodka Volume")]
        [Required]
        public float Volume { get; set; }

        [Display(Name = "Vodka Flavoured")]
        [Required]
        public string Flavoured { get; set; }

        [Display(Name = "Vodka Material")]
        [Required]
        public string Material { get; set; }

        [Display(Name = "Vodka Qualification")]
        [Required]
        public int Qualification { get; set; }
    }
}

OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Models/VodkasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VodkaDelivery.Web.Models
{
    public class VodkasViewModel
    {
        public Vodka EditedVodka { get; set; }
        public List<Vodka> ListOfVodkas { get; set; }
    }
}

OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Controllers/VodkaController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VodkaDelivery.Data;
using VodkaDelivery.Logic;
using VodkaDelivery.Repository;
using VodkaDelivery.Web.Models;

namespace VodkaDelivery.Web.Controllers
{
    public class VodkaController : Controller
    {
        IVodkaLogic logic;
        IMapper mapper;
        IMapper reverse;
        VodkasViewModel vm;

        public VodkaController()
        {
            vodkadeliverydatabaseEntities entities = new vodkadeliverydatabaseEntities();
            VodkaRepository vodkaRepo = new VodkaRepository(entities);
            logic = new VodkaLogic(vodkaRepo);
            mapper = MapperFactory.CreateMapper();
            reverse = MapperFactory.ReverseMapper();
            vm = new VodkasViewModel();
            vm.EditedVodka = new Models.Vodka();
            var vodkas = logic.GetVodkas();
            vm.ListOfVodkas = mapper.Map<IList<Data.Vodka>, List<Models.Vodka>>(vodkas);
        }

        private Models.Vodka GetVodkaModel(int id)
        {
            Data.Vodka oneVodka = logic.GetOne(id);
            return mapper.Map<Data.Vodka, Models.Vodka>(oneVodka);
        }

        private Data.Vodka GetVodkaData(Models.Vodka vodka)
        {
            return reverse.Map<Models.Vodka, Data.Vodka>(vodka);
        }

        private List<string> EditedVodkaDatas(Models.Vodka vodka)
        {
            List<string> toBack = new List<string>();
            toBack.Add(vodka.ID.ToString());
            toBack.Add(vodka.Company_ID.ToString());
            toBack.Add(vodka.VodkaName.ToString());
            toBack.Add(vodka.NumberOfDestills.ToString());
            toBack.Add(vodka.Price.ToString());
            toBack.Add(vodka.Volume.ToString());
            toBack.Add(vodka.Flavoured.ToString());
            toBack.Add(vodka.Material.ToString());
            toBack.Add(vodka.Qualification.ToString());
            return toBack;
        }

        // GET: Vodka
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("VodkaIndex", vm);
        }

        // GET: Vodka/Details/5
        public ActionResult Details(int id)
        {
            return View("VodkaDetails", GetVodkaModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.DeleteVodka(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedVodka = GetVodkaModel(id);
            return View("VodkaIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Models.Vodka vodka, string editAction)
        {
            if(ModelState.IsValid && vodka != null)
            {
                TempData["editResult"] = "Edit OK";
                if(editAction == "AddNew")
                {
                    logic.InsertIntoVodka(GetVodkaData(vodka));
                }
                else
                {
                    bool success = logic.UpdateVodka(vodka.ID, EditedVodkaDatas(vodka));
                    if(!success) TempData["editResult"] = "Edit FAIL";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedVodka = vodka;
                return View("VodkaIndex", vm);
            }
        }
    }
}

OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Views/Vodka/VodkaDetails.cshtml
@model VodkaDelivery.Web.Models.Vodka
@{
    ViewBag.Title = "VordkaDetails";
}

<h2>Datasheet of one car</h2>
@Html.ActionLink("Bactk to the list", "Index");

<table border="1">
    <tr>
        <td>The Id for the vodka</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Company_ID)</td>
        <td>@Html.DisplayFor(m => m.Company_ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.VodkaName)</td>
        <td>@Html.DisplayFor(m => m.VodkaName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.NumberOfDestills)</td>
        <td>@Html.DisplayFor(m => m.NumberOfDestills)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Volume)</td>
        <td>@Html.DisplayFor(m => m.Volume)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Flavoured)</td>
        <td>@Html.DisplayFor(m => m.Flavoured)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Material)</td>
        <td>@Html.DisplayFor(m => m.Material)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Qualification)</td>
        <td>@Html.DisplayFor(m => m.Qualification)</td>
    </tr>
</table>

OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Views/Vodka/VodkaEdit.cshtml
@model VodkaDelivery.Web.Models.Vodka

<h2>Edit one vodka</h2>

@using (Html.BeginForm("Edit", "Vodka"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Company_ID)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Company_ID)</div>

    <div class="editor-label">@Html.LabelFor(m => m.VodkaName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.VodkaName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.NumberOfDestills)</div>
    <div class="editor-field">@Html.EditorFor(m => m.NumberOfDestills)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Volume)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Volume)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Flavoured)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Flavoured)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Material)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Material)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Qualification)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Qualification)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Views/Vodka/VodkaIndex.cshtml
@model VodkaDelivery.Web.Models.VodkasViewModel
@{
    ViewBag.Title = "Vodka Index";
}

<h2>Vodka Index</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("VodkaEdit", Model.EditedVodka)

@Html.Partial("VodkaList", Model.ListOfVodkas)

OENIK_PROG4HF_2020_1_AFWFZZ/VodkaDelivery.Web/Views/Vodka/VodkaList.cshtml
@model IEnumerable<VodkaDelivery.Web.Models.Vodka>

<h2>List of Vodkas</h2>
@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Company_ID)</th>
            <th>@Html.DisplayNameFor(m => m.First().VodkaName)</th>
            <th>@Html.DisplayNameFor(m => m.First().NumberOfDestills)</th>
            <th>@Html.DisplayNameFor(m => m.First().Price)</th>
            <th>@Html.DisplayNameFor(m => m.First().Volume)</th>
            <th>@Html.DisplayNameFor(m => m.First().Flavoured)</th>
            <th>@Html.DisplayNameFor(m => m.First().Material)</th>
            <th>@Html.DisplayNameFor(m => m.First().Qualification)</th>
            <th>DataSheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Company_ID)</td>
                <td>@Html.DisplayFor(m => item.VodkaName)</td>
                <td>@Html.DisplayFor(m => item.NumberOfDestills)</td>
                <td>@Html.DisplayFor(m => item.Price)</td>
                <td>@Html.DisplayFor(m => item.Volume)</td>
                <td>@Html.DisplayFor(m => item.Flavoured)</td>
                <td>@Html.DisplayFor(m => item.Material)</td>
                <td>@Html.DisplayFor(m => item.Qualification)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID})</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
            </tr>
        }
    </table>
}